import type { LatestBookingType } from "../types"

export const latestBookingsData: LatestBookingType[] = [
  {
    id: "BK-10041",
    customerName: "Ahmed Al-Rashid",
    customerAvatar: "/images/avatars/male-01.svg",
    courtName: "Arena Court A",
    date: new Date("2026-05-14T09:00:00Z"),
    duration: 60,
    amount: 120,
    status: "Confirmed",
  },
  {
    id: "BK-10040",
    customerName: "Sara Al-Mansouri",
    customerAvatar: "/images/avatars/female-01.svg",
    courtName: "Sunset Field",
    date: new Date("2026-05-14T08:00:00Z"),
    duration: 90,
    amount: 180,
    status: "Confirmed",
  },
  {
    id: "BK-10039",
    customerName: "Khalid Nasser",
    customerAvatar: "/images/avatars/male-02.svg",
    courtName: "Indoor Pitch 1",
    date: new Date("2026-05-13T20:00:00Z"),
    duration: 60,
    amount: 100,
    status: "Completed",
  },
  {
    id: "BK-10038",
    customerName: "Lina Hassan",
    customerAvatar: "/images/avatars/female-02.svg",
    courtName: "Pro Arena",
    date: new Date("2026-05-13T18:00:00Z"),
    duration: 120,
    amount: 240,
    status: "Completed",
  },
  {
    id: "BK-10037",
    customerName: "Omar Zayed",
    customerAvatar: "/images/avatars/male-03.svg",
    courtName: "Arena Court B",
    date: new Date("2026-05-13T16:00:00Z"),
    duration: 60,
    amount: 110,
    status: "Cancelled",
  },
  {
    id: "BK-10036",
    customerName: "Nour Al-Sayed",
    customerAvatar: "/images/avatars/female-03.svg",
    courtName: "Sunset Field",
    date: new Date("2026-05-13T14:00:00Z"),
    duration: 90,
    amount: 175,
    status: "Pending",
  },
]
