import type { InvoiceType } from "../types"

export const invoicesData: InvoiceType[] = [
  {
    id: "INV001", status: "Paid", method: "Credit Card", amount: "$250.00", phone: "+1 (555) 123-0001",
    _id: "",
    name: "",
    description: "",
    sport: "",
    surface: "",
    size: "",
    capacity: 0,
    price: 0,
    currency: "",
    avatar: "",
    isActive: false,
    slotDurationMinutes: 0,
    bufferMinutes: 0,
    offersTraining: false,
    createdAt: "",
    updatedAt: "",
    location: {
      _id: "",
      city: "",
      area: "",
      district: "",
      address: "",
      locationId: "",
      latitude: 0,
      longitude: 0
    },
    owner: {
      _id: "",
      name: "",
      email: "",
      role: ""
    },
    amenities: []
  },
  {
    id: "INV002", status: "Pending", method: "PayPal", amount: "$150.00", phone: "+1 (555) 123-0002",
    _id: "",
    name: "",
    description: "",
    sport: "",
    surface: "",
    size: "",
    capacity: 0,
    price: 0,
    currency: "",
    avatar: "",
    isActive: false,
    slotDurationMinutes: 0,
    bufferMinutes: 0,
    offersTraining: false,
    createdAt: "",
    updatedAt: "",
    location: {
      _id: "",
      city: "",
      area: "",
      district: "",
      address: "",
      locationId: "",
      latitude: 0,
      longitude: 0
    },
    owner: {
      _id: "",
      name: "",
      email: "",
      role: ""
    },
    amenities: []
  },
  {
    id: "INV003", status: "Overdue", method: "Bank Transfer", amount: "$300.00", phone: "+1 (555) 123-0003",
    _id: "",
    name: "",
    description: "",
    sport: "",
    surface: "",
    size: "",
    capacity: 0,
    price: 0,
    currency: "",
    avatar: "",
    isActive: false,
    slotDurationMinutes: 0,
    bufferMinutes: 0,
    offersTraining: false,
    createdAt: "",
    updatedAt: "",
    location: {
      _id: "",
      city: "",
      area: "",
      district: "",
      address: "",
      locationId: "",
      latitude: 0,
      longitude: 0
    },
    owner: {
      _id: "",
      name: "",
      email: "",
      role: ""
    },
    amenities: []
  },

  {
    id: "INV004", status: "Paid", method: "Credit Card", amount: "$180.00", phone: "+1 (555) 123-0004",
    _id: "",
    name: "",
    description: "",
    sport: "",
    surface: "",
    size: "",
    capacity: 0,
    price: 0,
    currency: "",
    avatar: "",
    isActive: false,
    slotDurationMinutes: 0,
    bufferMinutes: 0,
    offersTraining: false,
    createdAt: "",
    updatedAt: "",
    location: {
      _id: "",
      city: "",
      area: "",
      district: "",
      address: "",
      locationId: "",
      latitude: 0,
      longitude: 0
    },
    owner: {
      _id: "",
      name: "",
      email: "",
      role: ""
    },
    amenities: []
  },
  {
    id: "INV005", status: "Pending", method: "Bank Transfer", amount: "$220.00", phone: "+1 (555) 123-0005",
    _id: "",
    name: "",
    description: "",
    sport: "",
    surface: "",
    size: "",
    capacity: 0,
    price: 0,
    currency: "",
    avatar: "",
    isActive: false,
    slotDurationMinutes: 0,
    bufferMinutes: 0,
    offersTraining: false,
    createdAt: "",
    updatedAt: "",
    location: {
      _id: "",
      city: "",
      area: "",
      district: "",
      address: "",
      locationId: "",
      latitude: 0,
      longitude: 0
    },
    owner: {
      _id: "",
      name: "",
      email: "",
      role: ""
    },
    amenities: []
  },
  {
    id: "INV006", status: "Overdue", method: "PayPal", amount: "$90.00", phone: "+1 (555) 123-0006",
    _id: "",
    name: "",
    description: "",
    sport: "",
    surface: "",
    size: "",
    capacity: 0,
    price: 0,
    currency: "",
    avatar: "",
    isActive: false,
    slotDurationMinutes: 0,
    bufferMinutes: 0,
    offersTraining: false,
    createdAt: "",
    updatedAt: "",
    location: {
      _id: "",
      city: "",
      area: "",
      district: "",
      address: "",
      locationId: "",
      latitude: 0,
      longitude: 0
    },
    owner: {
      _id: "",
      name: "",
      email: "",
      role: ""
    },
    amenities: []
  },
  {
    id: "INV007", status: "Paid", method: "PayPal", amount: "$310.00", phone: "+1 (555) 123-0007",
    _id: "",
    name: "",
    description: "",
    sport: "",
    surface: "",
    size: "",
    capacity: 0,
    price: 0,
    currency: "",
    avatar: "",
    isActive: false,
    slotDurationMinutes: 0,
    bufferMinutes: 0,
    offersTraining: false,
    createdAt: "",
    updatedAt: "",
    location: {
      _id: "",
      city: "",
      area: "",
      district: "",
      address: "",
      locationId: "",
      latitude: 0,
      longitude: 0
    },
    owner: {
      _id: "",
      name: "",
      email: "",
      role: ""
    },
    amenities: []
  },
  {
    id: "INV008", status: "Pending", method: "Credit Card", amount: "$145.00", phone: "+1 (555) 123-0008",
    _id: "",
    name: "",
    description: "",
    sport: "",
    surface: "",
    size: "",
    capacity: 0,
    price: 0,
    currency: "",
    avatar: "",
    isActive: false,
    slotDurationMinutes: 0,
    bufferMinutes: 0,
    offersTraining: false,
    createdAt: "",
    updatedAt: "",
    location: {
      _id: "",
      city: "",
      area: "",
      district: "",
      address: "",
      locationId: "",
      latitude: 0,
      longitude: 0
    },
    owner: {
      _id: "",
      name: "",
      email: "",
      role: ""
    },
    amenities: []
  },
  {
    id: "INV009", status: "Overdue", method: "Bank Transfer", amount: "$275.00", phone: "+1 (555) 123-0009",
    _id: "",
    name: "",
    description: "",
    sport: "",
    surface: "",
    size: "",
    capacity: 0,
    price: 0,
    currency: "",
    avatar: "",
    isActive: false,
    slotDurationMinutes: 0,
    bufferMinutes: 0,
    offersTraining: false,
    createdAt: "",
    updatedAt: "",
    location: {
      _id: "",
      city: "",
      area: "",
      district: "",
      address: "",
      locationId: "",
      latitude: 0,
      longitude: 0
    },
    owner: {
      _id: "",
      name: "",
      email: "",
      role: ""
    },
    amenities: []
  },
  {
    id: "INV010", status: "Paid", method: "Credit Card", amount: "$500.00", phone: "+1 (555) 123-0010",
    _id: "",
    name: "",
    description: "",
    sport: "",
    surface: "",
    size: "",
    capacity: 0,
    price: 0,
    currency: "",
    avatar: "",
    isActive: false,
    slotDurationMinutes: 0,
    bufferMinutes: 0,
    offersTraining: false,
    createdAt: "",
    updatedAt: "",
    location: {
      _id: "",
      city: "",
      area: "",
      district: "",
      address: "",
      locationId: "",
      latitude: 0,
      longitude: 0
    },
    owner: {
      _id: "",
      name: "",
      email: "",
      role: ""
    },
    amenities: []
  },

  {
    id: "INV011", status: "Pending", method: "PayPal", amount: "$130.00", phone: "+1 (555) 123-0011",
    _id: "",
    name: "",
    description: "",
    sport: "",
    surface: "",
    size: "",
    capacity: 0,
    price: 0,
    currency: "",
    avatar: "",
    isActive: false,
    slotDurationMinutes: 0,
    bufferMinutes: 0,
    offersTraining: false,
    createdAt: "",
    updatedAt: "",
    location: {
      _id: "",
      city: "",
      area: "",
      district: "",
      address: "",
      locationId: "",
      latitude: 0,
      longitude: 0
    },
    owner: {
      _id: "",
      name: "",
      email: "",
      role: ""
    },
    amenities: []
  },
  {
    id: "INV012", status: "Paid", method: "Bank Transfer", amount: "$410.00", phone: "+1 (555) 123-0012",
    _id: "",
    name: "",
    description: "",
    sport: "",
    surface: "",
    size: "",
    capacity: 0,
    price: 0,
    currency: "",
    avatar: "",
    isActive: false,
    slotDurationMinutes: 0,
    bufferMinutes: 0,
    offersTraining: false,
    createdAt: "",
    updatedAt: "",
    location: {
      _id: "",
      city: "",
      area: "",
      district: "",
      address: "",
      locationId: "",
      latitude: 0,
      longitude: 0
    },
    owner: {
      _id: "",
      name: "",
      email: "",
      role: ""
    },
    amenities: []
  },
  {
    id: "INV013", status: "Overdue", method: "Credit Card", amount: "$260.00", phone: "+1 (555) 123-0013",
    _id: "",
    name: "",
    description: "",
    sport: "",
    surface: "",
    size: "",
    capacity: 0,
    price: 0,
    currency: "",
    avatar: "",
    isActive: false,
    slotDurationMinutes: 0,
    bufferMinutes: 0,
    offersTraining: false,
    createdAt: "",
    updatedAt: "",
    location: {
      _id: "",
      city: "",
      area: "",
      district: "",
      address: "",
      locationId: "",
      latitude: 0,
      longitude: 0
    },
    owner: {
      _id: "",
      name: "",
      email: "",
      role: ""
    },
    amenities: []
  },
  {
    id: "INV014", status: "Paid", method: "PayPal", amount: "$350.00", phone: "+1 (555) 123-0014",
    _id: "",
    name: "",
    description: "",
    sport: "",
    surface: "",
    size: "",
    capacity: 0,
    price: 0,
    currency: "",
    avatar: "",
    isActive: false,
    slotDurationMinutes: 0,
    bufferMinutes: 0,
    offersTraining: false,
    createdAt: "",
    updatedAt: "",
    location: {
      _id: "",
      city: "",
      area: "",
      district: "",
      address: "",
      locationId: "",
      latitude: 0,
      longitude: 0
    },
    owner: {
      _id: "",
      name: "",
      email: "",
      role: ""
    },
    amenities: []
  },
  {
    id: "INV015", status: "Pending", method: "Credit Card", amount: "$200.00", phone: "+1 (555) 123-0015",
    _id: "",
    name: "",
    description: "",
    sport: "",
    surface: "",
    size: "",
    capacity: 0,
    price: 0,
    currency: "",
    avatar: "",
    isActive: false,
    slotDurationMinutes: 0,
    bufferMinutes: 0,
    offersTraining: false,
    createdAt: "",
    updatedAt: "",
    location: {
      _id: "",
      city: "",
      area: "",
      district: "",
      address: "",
      locationId: "",
      latitude: 0,
      longitude: 0
    },
    owner: {
      _id: "",
      name: "",
      email: "",
      role: ""
    },
    amenities: []
  },
  {
    id: "INV016", status: "Overdue", method: "Bank Transfer", amount: "$320.00", phone: "+1 (555) 123-0016",
    _id: "",
    name: "",
    description: "",
    sport: "",
    surface: "",
    size: "",
    capacity: 0,
    price: 0,
    currency: "",
    avatar: "",
    isActive: false,
    slotDurationMinutes: 0,
    bufferMinutes: 0,
    offersTraining: false,
    createdAt: "",
    updatedAt: "",
    location: {
      _id: "",
      city: "",
      area: "",
      district: "",
      address: "",
      locationId: "",
      latitude: 0,
      longitude: 0
    },
    owner: {
      _id: "",
      name: "",
      email: "",
      role: ""
    },
    amenities: []
  },
  {
    id: "INV017", status: "Paid", method: "Credit Card", amount: "$175.00", phone: "+1 (555) 123-0017",
    _id: "",
    name: "",
    description: "",
    sport: "",
    surface: "",
    size: "",
    capacity: 0,
    price: 0,
    currency: "",
    avatar: "",
    isActive: false,
    slotDurationMinutes: 0,
    bufferMinutes: 0,
    offersTraining: false,
    createdAt: "",
    updatedAt: "",
    location: {
      _id: "",
      city: "",
      area: "",
      district: "",
      address: "",
      locationId: "",
      latitude: 0,
      longitude: 0
    },
    owner: {
      _id: "",
      name: "",
      email: "",
      role: ""
    },
    amenities: []
  },
  {
    id: "INV018", status: "Pending", method: "PayPal", amount: "$95.00", phone: "+1 (555) 123-0018",
    _id: "",
    name: "",
    description: "",
    sport: "",
    surface: "",
    size: "",
    capacity: 0,
    price: 0,
    currency: "",
    avatar: "",
    isActive: false,
    slotDurationMinutes: 0,
    bufferMinutes: 0,
    offersTraining: false,
    createdAt: "",
    updatedAt: "",
    location: {
      _id: "",
      city: "",
      area: "",
      district: "",
      address: "",
      locationId: "",
      latitude: 0,
      longitude: 0
    },
    owner: {
      _id: "",
      name: "",
      email: "",
      role: ""
    },
    amenities: []
  },
  {
    id: "INV019", status: "Overdue", method: "Credit Card", amount: "$440.00", phone: "+1 (555) 123-0019",
    _id: "",
    name: "",
    description: "",
    sport: "",
    surface: "",
    size: "",
    capacity: 0,
    price: 0,
    currency: "",
    avatar: "",
    isActive: false,
    slotDurationMinutes: 0,
    bufferMinutes: 0,
    offersTraining: false,
    createdAt: "",
    updatedAt: "",
    location: {
      _id: "",
      city: "",
      area: "",
      district: "",
      address: "",
      locationId: "",
      latitude: 0,
      longitude: 0
    },
    owner: {
      _id: "",
      name: "",
      email: "",
      role: ""
    },
    amenities: []
  },
  {
    id: "INV020", status: "Paid", method: "Bank Transfer", amount: "$510.00", phone: "+1 (555) 123-0020",
    _id: "",
    name: "",
    description: "",
    sport: "",
    surface: "",
    size: "",
    capacity: 0,
    price: 0,
    currency: "",
    avatar: "",
    isActive: false,
    slotDurationMinutes: 0,
    bufferMinutes: 0,
    offersTraining: false,
    createdAt: "",
    updatedAt: "",
    location: {
      _id: "",
      city: "",
      area: "",
      district: "",
      address: "",
      locationId: "",
      latitude: 0,
      longitude: 0
    },
    owner: {
      _id: "",
      name: "",
      email: "",
      role: ""
    },
    amenities: []
  },

  {
    id: "INV021", status: "Pending", method: "Credit Card", amount: "$210.00", phone: "+1 (555) 123-0021",
    _id: "",
    name: "",
    description: "",
    sport: "",
    surface: "",
    size: "",
    capacity: 0,
    price: 0,
    currency: "",
    avatar: "",
    isActive: false,
    slotDurationMinutes: 0,
    bufferMinutes: 0,
    offersTraining: false,
    createdAt: "",
    updatedAt: "",
    location: {
      _id: "",
      city: "",
      area: "",
      district: "",
      address: "",
      locationId: "",
      latitude: 0,
      longitude: 0
    },
    owner: {
      _id: "",
      name: "",
      email: "",
      role: ""
    },
    amenities: []
  },
  {
    id: "INV022", status: "Paid", method: "PayPal", amount: "$330.00", phone: "+1 (555) 123-0022",
    _id: "",
    name: "",
    description: "",
    sport: "",
    surface: "",
    size: "",
    capacity: 0,
    price: 0,
    currency: "",
    avatar: "",
    isActive: false,
    slotDurationMinutes: 0,
    bufferMinutes: 0,
    offersTraining: false,
    createdAt: "",
    updatedAt: "",
    location: {
      _id: "",
      city: "",
      area: "",
      district: "",
      address: "",
      locationId: "",
      latitude: 0,
      longitude: 0
    },
    owner: {
      _id: "",
      name: "",
      email: "",
      role: ""
    },
    amenities: []
  },
  {
    id: "INV023", status: "Overdue", method: "Bank Transfer", amount: "$120.00", phone: "+1 (555) 123-0023",
    _id: "",
    name: "",
    description: "",
    sport: "",
    surface: "",
    size: "",
    capacity: 0,
    price: 0,
    currency: "",
    avatar: "",
    isActive: false,
    slotDurationMinutes: 0,
    bufferMinutes: 0,
    offersTraining: false,
    createdAt: "",
    updatedAt: "",
    location: {
      _id: "",
      city: "",
      area: "",
      district: "",
      address: "",
      locationId: "",
      latitude: 0,
      longitude: 0
    },
    owner: {
      _id: "",
      name: "",
      email: "",
      role: ""
    },
    amenities: []
  },
  {
    id: "INV024", status: "Pending", method: "PayPal", amount: "$260.00", phone: "+1 (555) 123-0024",
    _id: "",
    name: "",
    description: "",
    sport: "",
    surface: "",
    size: "",
    capacity: 0,
    price: 0,
    currency: "",
    avatar: "",
    isActive: false,
    slotDurationMinutes: 0,
    bufferMinutes: 0,
    offersTraining: false,
    createdAt: "",
    updatedAt: "",
    location: {
      _id: "",
      city: "",
      area: "",
      district: "",
      address: "",
      locationId: "",
      latitude: 0,
      longitude: 0
    },
    owner: {
      _id: "",
      name: "",
      email: "",
      role: ""
    },
    amenities: []
  },
  {
    id: "INV025", status: "Paid", method: "Credit Card", amount: "$480.00", phone: "+1 (555) 123-0025",
    _id: "",
    name: "",
    description: "",
    sport: "",
    surface: "",
    size: "",
    capacity: 0,
    price: 0,
    currency: "",
    avatar: "",
    isActive: false,
    slotDurationMinutes: 0,
    bufferMinutes: 0,
    offersTraining: false,
    createdAt: "",
    updatedAt: "",
    location: {
      _id: "",
      city: "",
      area: "",
      district: "",
      address: "",
      locationId: "",
      latitude: 0,
      longitude: 0
    },
    owner: {
      _id: "",
      name: "",
      email: "",
      role: ""
    },
    amenities: []
  },
  {
    id: "INV026", status: "Overdue", method: "Bank Transfer", amount: "$140.00", phone: "+1 (555) 123-0026",
    _id: "",
    name: "",
    description: "",
    sport: "",
    surface: "",
    size: "",
    capacity: 0,
    price: 0,
    currency: "",
    avatar: "",
    isActive: false,
    slotDurationMinutes: 0,
    bufferMinutes: 0,
    offersTraining: false,
    createdAt: "",
    updatedAt: "",
    location: {
      _id: "",
      city: "",
      area: "",
      district: "",
      address: "",
      locationId: "",
      latitude: 0,
      longitude: 0
    },
    owner: {
      _id: "",
      name: "",
      email: "",
      role: ""
    },
    amenities: []
  },
  {
    id: "INV027", status: "Pending", method: "Credit Card", amount: "$295.00", phone: "+1 (555) 123-0027",
    _id: "",
    name: "",
    description: "",
    sport: "",
    surface: "",
    size: "",
    capacity: 0,
    price: 0,
    currency: "",
    avatar: "",
    isActive: false,
    slotDurationMinutes: 0,
    bufferMinutes: 0,
    offersTraining: false,
    createdAt: "",
    updatedAt: "",
    location: {
      _id: "",
      city: "",
      area: "",
      district: "",
      address: "",
      locationId: "",
      latitude: 0,
      longitude: 0
    },
    owner: {
      _id: "",
      name: "",
      email: "",
      role: ""
    },
    amenities: []
  },
  {
    id: "INV028", status: "Paid", method: "Bank Transfer", amount: "$390.00", phone: "+1 (555) 123-0028",
    _id: "",
    name: "",
    description: "",
    sport: "",
    surface: "",
    size: "",
    capacity: 0,
    price: 0,
    currency: "",
    avatar: "",
    isActive: false,
    slotDurationMinutes: 0,
    bufferMinutes: 0,
    offersTraining: false,
    createdAt: "",
    updatedAt: "",
    location: {
      _id: "",
      city: "",
      area: "",
      district: "",
      address: "",
      locationId: "",
      latitude: 0,
      longitude: 0
    },
    owner: {
      _id: "",
      name: "",
      email: "",
      role: ""
    },
    amenities: []
  },
  {
    id: "INV029", status: "Overdue", method: "Credit Card", amount: "$165.00", phone: "+1 (555) 123-0029",
    _id: "",
    name: "",
    description: "",
    sport: "",
    surface: "",
    size: "",
    capacity: 0,
    price: 0,
    currency: "",
    avatar: "",
    isActive: false,
    slotDurationMinutes: 0,
    bufferMinutes: 0,
    offersTraining: false,
    createdAt: "",
    updatedAt: "",
    location: {
      _id: "",
      city: "",
      area: "",
      district: "",
      address: "",
      locationId: "",
      latitude: 0,
      longitude: 0
    },
    owner: {
      _id: "",
      name: "",
      email: "",
      role: ""
    },
    amenities: []
  },
  {
    id: "INV030", status: "Paid", method: "PayPal", amount: "$520.00", phone: "+1 (555) 123-0030",
    _id: "",
    name: "",
    description: "",
    sport: "",
    surface: "",
    size: "",
    capacity: 0,
    price: 0,
    currency: "",
    avatar: "",
    isActive: false,
    slotDurationMinutes: 0,
    bufferMinutes: 0,
    offersTraining: false,
    createdAt: "",
    updatedAt: "",
    location: {
      _id: "",
      city: "",
      area: "",
      district: "",
      address: "",
      locationId: "",
      latitude: 0,
      longitude: 0
    },
    owner: {
      _id: "",
      name: "",
      email: "",
      role: ""
    },
    amenities: []
  },

  {
    id: "INV031", status: "Pending", method: "Bank Transfer", amount: "$250.00", phone: "+1 (555) 123-0031",
    _id: "",
    name: "",
    description: "",
    sport: "",
    surface: "",
    size: "",
    capacity: 0,
    price: 0,
    currency: "",
    avatar: "",
    isActive: false,
    slotDurationMinutes: 0,
    bufferMinutes: 0,
    offersTraining: false,
    createdAt: "",
    updatedAt: "",
    location: {
      _id: "",
      city: "",
      area: "",
      district: "",
      address: "",
      locationId: "",
      latitude: 0,
      longitude: 0
    },
    owner: {
      _id: "",
      name: "",
      email: "",
      role: ""
    },
    amenities: []
  },
  {
    id: "INV032", status: "Overdue", method: "PayPal", amount: "$110.00", phone: "+1 (555) 123-0032",
    _id: "",
    name: "",
    description: "",
    sport: "",
    surface: "",
    size: "",
    capacity: 0,
    price: 0,
    currency: "",
    avatar: "",
    isActive: false,
    slotDurationMinutes: 0,
    bufferMinutes: 0,
    offersTraining: false,
    createdAt: "",
    updatedAt: "",
    location: {
      _id: "",
      city: "",
      area: "",
      district: "",
      address: "",
      locationId: "",
      latitude: 0,
      longitude: 0
    },
    owner: {
      _id: "",
      name: "",
      email: "",
      role: ""
    },
    amenities: []
  },
  {
    id: "INV033", status: "Paid", method: "Credit Card", amount: "$275.00", phone: "+1 (555) 123-0033",
    _id: "",
    name: "",
    description: "",
    sport: "",
    surface: "",
    size: "",
    capacity: 0,
    price: 0,
    currency: "",
    avatar: "",
    isActive: false,
    slotDurationMinutes: 0,
    bufferMinutes: 0,
    offersTraining: false,
    createdAt: "",
    updatedAt: "",
    location: {
      _id: "",
      city: "",
      area: "",
      district: "",
      address: "",
      locationId: "",
      latitude: 0,
      longitude: 0
    },
    owner: {
      _id: "",
      name: "",
      email: "",
      role: ""
    },
    amenities: []
  },
  {
    id: "INV034", status: "Pending", method: "PayPal", amount: "$305.00", phone: "+1 (555) 123-0034",
    _id: "",
    name: "",
    description: "",
    sport: "",
    surface: "",
    size: "",
    capacity: 0,
    price: 0,
    currency: "",
    avatar: "",
    isActive: false,
    slotDurationMinutes: 0,
    bufferMinutes: 0,
    offersTraining: false,
    createdAt: "",
    updatedAt: "",
    location: {
      _id: "",
      city: "",
      area: "",
      district: "",
      address: "",
      locationId: "",
      latitude: 0,
      longitude: 0
    },
    owner: {
      _id: "",
      name: "",
      email: "",
      role: ""
    },
    amenities: []
  },
  {
    id: "INV035", status: "Paid", method: "Bank Transfer", amount: "$455.00", phone: "+1 (555) 123-0035",
    _id: "",
    name: "",
    description: "",
    sport: "",
    surface: "",
    size: "",
    capacity: 0,
    price: 0,
    currency: "",
    avatar: "",
    isActive: false,
    slotDurationMinutes: 0,
    bufferMinutes: 0,
    offersTraining: false,
    createdAt: "",
    updatedAt: "",
    location: {
      _id: "",
      city: "",
      area: "",
      district: "",
      address: "",
      locationId: "",
      latitude: 0,
      longitude: 0
    },
    owner: {
      _id: "",
      name: "",
      email: "",
      role: ""
    },
    amenities: []
  },
  {
    id: "INV036", status: "Overdue", method: "Credit Card", amount: "$190.00", phone: "+1 (555) 123-0036",
    _id: "",
    name: "",
    description: "",
    sport: "",
    surface: "",
    size: "",
    capacity: 0,
    price: 0,
    currency: "",
    avatar: "",
    isActive: false,
    slotDurationMinutes: 0,
    bufferMinutes: 0,
    offersTraining: false,
    createdAt: "",
    updatedAt: "",
    location: {
      _id: "",
      city: "",
      area: "",
      district: "",
      address: "",
      locationId: "",
      latitude: 0,
      longitude: 0
    },
    owner: {
      _id: "",
      name: "",
      email: "",
      role: ""
    },
    amenities: []
  },
  {
    id: "INV037", status: "Paid", method: "PayPal", amount: "$600.00", phone: "+1 (555) 123-0037",
    _id: "",
    name: "",
    description: "",
    sport: "",
    surface: "",
    size: "",
    capacity: 0,
    price: 0,
    currency: "",
    avatar: "",
    isActive: false,
    slotDurationMinutes: 0,
    bufferMinutes: 0,
    offersTraining: false,
    createdAt: "",
    updatedAt: "",
    location: {
      _id: "",
      city: "",
      area: "",
      district: "",
      address: "",
      locationId: "",
      latitude: 0,
      longitude: 0
    },
    owner: {
      _id: "",
      name: "",
      email: "",
      role: ""
    },
    amenities: []
  },
  {
    id: "INV038", status: "Pending", method: "Credit Card", amount: "$280.00", phone: "+1 (555) 123-0038",
    _id: "",
    name: "",
    description: "",
    sport: "",
    surface: "",
    size: "",
    capacity: 0,
    price: 0,
    currency: "",
    avatar: "",
    isActive: false,
    slotDurationMinutes: 0,
    bufferMinutes: 0,
    offersTraining: false,
    createdAt: "",
    updatedAt: "",
    location: {
      _id: "",
      city: "",
      area: "",
      district: "",
      address: "",
      locationId: "",
      latitude: 0,
      longitude: 0
    },
    owner: {
      _id: "",
      name: "",
      email: "",
      role: ""
    },
    amenities: []
  },
  {
    id: "INV039", status: "Overdue", method: "Bank Transfer", amount: "$135.00", phone: "+1 (555) 123-0039",
    _id: "",
    name: "",
    description: "",
    sport: "",
    surface: "",
    size: "",
    capacity: 0,
    price: 0,
    currency: "",
    avatar: "",
    isActive: false,
    slotDurationMinutes: 0,
    bufferMinutes: 0,
    offersTraining: false,
    createdAt: "",
    updatedAt: "",
    location: {
      _id: "",
      city: "",
      area: "",
      district: "",
      address: "",
      locationId: "",
      latitude: 0,
      longitude: 0
    },
    owner: {
      _id: "",
      name: "",
      email: "",
      role: ""
    },
    amenities: []
  },
  {
    id: "INV040", status: "Paid", method: "PayPal", amount: "$340.00", phone: "+1 (555) 123-0040",
    _id: "",
    name: "",
    description: "",
    sport: "",
    surface: "",
    size: "",
    capacity: 0,
    price: 0,
    currency: "",
    avatar: "",
    isActive: false,
    slotDurationMinutes: 0,
    bufferMinutes: 0,
    offersTraining: false,
    createdAt: "",
    updatedAt: "",
    location: {
      _id: "",
      city: "",
      area: "",
      district: "",
      address: "",
      locationId: "",
      latitude: 0,
      longitude: 0
    },
    owner: {
      _id: "",
      name: "",
      email: "",
      role: ""
    },
    amenities: []
  },

  {
    id: "INV041", status: "Pending", method: "Credit Card", amount: "$150.00", phone: "+1 (555) 123-0041",
    _id: "",
    name: "",
    description: "",
    sport: "",
    surface: "",
    size: "",
    capacity: 0,
    price: 0,
    currency: "",
    avatar: "",
    isActive: false,
    slotDurationMinutes: 0,
    bufferMinutes: 0,
    offersTraining: false,
    createdAt: "",
    updatedAt: "",
    location: {
      _id: "",
      city: "",
      area: "",
      district: "",
      address: "",
      locationId: "",
      latitude: 0,
      longitude: 0
    },
    owner: {
      _id: "",
      name: "",
      email: "",
      role: ""
    },
    amenities: []
  },
  {
    id: "INV042", status: "Paid", method: "Bank Transfer", amount: "$470.00", phone: "+1 (555) 123-0042",
    _id: "",
    name: "",
    description: "",
    sport: "",
    surface: "",
    size: "",
    capacity: 0,
    price: 0,
    currency: "",
    avatar: "",
    isActive: false,
    slotDurationMinutes: 0,
    bufferMinutes: 0,
    offersTraining: false,
    createdAt: "",
    updatedAt: "",
    location: {
      _id: "",
      city: "",
      area: "",
      district: "",
      address: "",
      locationId: "",
      latitude: 0,
      longitude: 0
    },
    owner: {
      _id: "",
      name: "",
      email: "",
      role: ""
    },
    amenities: []
  },
  {
    id: "INV043", status: "Overdue", method: "Credit Card", amount: "$210.00", phone: "+1 (555) 123-0043",
    _id: "",
    name: "",
    description: "",
    sport: "",
    surface: "",
    size: "",
    capacity: 0,
    price: 0,
    currency: "",
    avatar: "",
    isActive: false,
    slotDurationMinutes: 0,
    bufferMinutes: 0,
    offersTraining: false,
    createdAt: "",
    updatedAt: "",
    location: {
      _id: "",
      city: "",
      area: "",
      district: "",
      address: "",
      locationId: "",
      latitude: 0,
      longitude: 0
    },
    owner: {
      _id: "",
      name: "",
      email: "",
      role: ""
    },
    amenities: []
  },
  {
    id: "INV044", status: "Pending", method: "PayPal", amount: "$125.00", phone: "+1 (555) 123-0044",
    _id: "",
    name: "",
    description: "",
    sport: "",
    surface: "",
    size: "",
    capacity: 0,
    price: 0,
    currency: "",
    avatar: "",
    isActive: false,
    slotDurationMinutes: 0,
    bufferMinutes: 0,
    offersTraining: false,
    createdAt: "",
    updatedAt: "",
    location: {
      _id: "",
      city: "",
      area: "",
      district: "",
      address: "",
      locationId: "",
      latitude: 0,
      longitude: 0
    },
    owner: {
      _id: "",
      name: "",
      email: "",
      role: ""
    },
    amenities: []
  },
  {
    id: "INV045", status: "Paid", method: "Credit Card", amount: "$510.00", phone: "+1 (555) 123-0045",
    _id: "",
    name: "",
    description: "",
    sport: "",
    surface: "",
    size: "",
    capacity: 0,
    price: 0,
    currency: "",
    avatar: "",
    isActive: false,
    slotDurationMinutes: 0,
    bufferMinutes: 0,
    offersTraining: false,
    createdAt: "",
    updatedAt: "",
    location: {
      _id: "",
      city: "",
      area: "",
      district: "",
      address: "",
      locationId: "",
      latitude: 0,
      longitude: 0
    },
    owner: {
      _id: "",
      name: "",
      email: "",
      role: ""
    },
    amenities: []
  },
  {
    id: "INV046", status: "Overdue", method: "Bank Transfer", amount: "$155.00", phone: "+1 (555) 123-0046",
    _id: "",
    name: "",
    description: "",
    sport: "",
    surface: "",
    size: "",
    capacity: 0,
    price: 0,
    currency: "",
    avatar: "",
    isActive: false,
    slotDurationMinutes: 0,
    bufferMinutes: 0,
    offersTraining: false,
    createdAt: "",
    updatedAt: "",
    location: {
      _id: "",
      city: "",
      area: "",
      district: "",
      address: "",
      locationId: "",
      latitude: 0,
      longitude: 0
    },
    owner: {
      _id: "",
      name: "",
      email: "",
      role: ""
    },
    amenities: []
  },
  {
    id: "INV047", status: "Pending", method: "PayPal", amount: "$350.00", phone: "+1 (555) 123-0047",
    _id: "",
    name: "",
    description: "",
    sport: "",
    surface: "",
    size: "",
    capacity: 0,
    price: 0,
    currency: "",
    avatar: "",
    isActive: false,
    slotDurationMinutes: 0,
    bufferMinutes: 0,
    offersTraining: false,
    createdAt: "",
    updatedAt: "",
    location: {
      _id: "",
      city: "",
      area: "",
      district: "",
      address: "",
      locationId: "",
      latitude: 0,
      longitude: 0
    },
    owner: {
      _id: "",
      name: "",
      email: "",
      role: ""
    },
    amenities: []
  },
  {
    id: "INV048", status: "Paid", method: "Credit Card", amount: "$420.00", phone: "+1 (555) 123-0048",
    _id: "",
    name: "",
    description: "",
    sport: "",
    surface: "",
    size: "",
    capacity: 0,
    price: 0,
    currency: "",
    avatar: "",
    isActive: false,
    slotDurationMinutes: 0,
    bufferMinutes: 0,
    offersTraining: false,
    createdAt: "",
    updatedAt: "",
    location: {
      _id: "",
      city: "",
      area: "",
      district: "",
      address: "",
      locationId: "",
      latitude: 0,
      longitude: 0
    },
    owner: {
      _id: "",
      name: "",
      email: "",
      role: ""
    },
    amenities: []
  },
  {
    id: "INV049", status: "Overdue", method: "PayPal", amount: "$180.00", phone: "+1 (555) 123-0049",
    _id: "",
    name: "",
    description: "",
    sport: "",
    surface: "",
    size: "",
    capacity: 0,
    price: 0,
    currency: "",
    avatar: "",
    isActive: false,
    slotDurationMinutes: 0,
    bufferMinutes: 0,
    offersTraining: false,
    createdAt: "",
    updatedAt: "",
    location: {
      _id: "",
      city: "",
      area: "",
      district: "",
      address: "",
      locationId: "",
      latitude: 0,
      longitude: 0
    },
    owner: {
      _id: "",
      name: "",
      email: "",
      role: ""
    },
    amenities: []
  },
  {
    id: "INV050", status: "Paid", method: "Bank Transfer", amount: "$560.00", phone: "+1 (555) 123-0050",
    _id: "",
    name: "",
    description: "",
    sport: "",
    surface: "",
    size: "",
    capacity: 0,
    price: 0,
    currency: "",
    avatar: "",
    isActive: false,
    slotDurationMinutes: 0,
    bufferMinutes: 0,
    offersTraining: false,
    createdAt: "",
    updatedAt: "",
    location: {
      _id: "",
      city: "",
      area: "",
      district: "",
      address: "",
      locationId: "",
      latitude: 0,
      longitude: 0
    },
    owner: {
      _id: "",
      name: "",
      email: "",
      role: ""
    },
    amenities: []
  }
];

